//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apitienda.Data
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class familias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public familias()
        {
            this.productos = new HashSet<productos>();
        }
    
        public int id { get; set; }
        public string numero_familia { get; set; }
        public string nombre { get; set; }
        public int id_clase { get; set; }

        [JsonIgnore]
        public virtual clases clases { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos> productos { get; set; }
    }
}
